// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Lớp cung cấp cấu hình [FirebaseOptions] mặc định cho ứng dụng.
/// File này được tạo tự động bởi FlutterFire CLI.
/// Không nên sửa tay cấu hình trong này trừ khi thật sự cần thiết.
/// 
/// Ví dụ khởi tạo:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtlmRjJ86QToHoEJZWxS4NBQ3Oe0PNcoc',
    appId: '1:662318155311:android:2dc56bf5b9d2b087ffa8da',
    messagingSenderId: '662318155311',
    projectId: 'english-app-55079',
    storageBucket: 'english-app-55079.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdf0WgLklCom8J2zpvnXcpnD-WvDidtR8',
    appId: '1:662318155311:ios:3afce647e0179febffa8da',
    messagingSenderId: '662318155311',
    projectId: 'english-app-55079',
    storageBucket: 'english-app-55079.firebasestorage.app',
    iosBundleId: 'com.example.vocabup',
  );

}